---
Name: somar_search_routes
After:
  - "#rootroutes"
  - "#coreroutes"
  - framework/routes#coreroutes
---
SilverStripe\Control\Director:
  rules:
    search: Somar\Search\Control\SearchPageController
